### ISSUE TITLE
wondering if there is support for make/cmake

### ISSUE THREAD

**Issue by willmafh** [census-instrumentation/opencensus-cpp#150]
Is there any plan for building opencensus-cpp by using make/cmake, the build tool bazel is strange to me, I've spent a lot of time to figure out how to build it correctly...But it seems still confusing...Any chance that I can use the familiar work flow to just make and build it into a library...Thanks...

**Comment by isturdy** [comment]
See #86--this is definitely in our plans but until our dependencies (particularly abseil) implement cmake support it is hard for us to move ahead.
