### ISSUE TITLE
As a user of opencensus-cpp, I'd want dependent library locked to specific version

### ISSUE THREAD

**Issue by StevenYCChou** [census-instrumentation/opencensus-cpp#250]
Currently, opencensus-cpp uses multiple upstream libraries, including abseil, gmock, gtest, prometheus-cpp. However, when we pulled in these dependent libraries, we pulled off from `master`. As a user of opencensus-cpp, if I want to build opencensus-cpp library from scratch, I may get different result from time to time. 

Therefore, I suggest locking down the version for both bazel and CMake for each opencensus-cpp release.

for bazel, an example is the [Bazel's absl dependent](https://github.com/census-instrumentation/opencensus-cpp/blob/bd876f63a728e2334cfe986eda9f4837bebe630e/WORKSPACE#L21):
from
```
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
```
to
```
    urls = ["https://github.com/abseil/abseil-cpp/archive/20180600.zip"],
```

for [Cmake's absl dependent](https://github.com/census-instrumentation/opencensus-cpp/blob/bd876f63a728e2334cfe986eda9f4837bebe630e/cmake/CMakeLists.txt#22), from
```
	GIT_TAG "master"
```
to
```
	GIT_TAG "20180600"
```

**Comment by g-easy** [comment]
Done.
