### ISSUE TITLE
MSVC version supported

### ISSUE THREAD

**Issue by meastp** [census-instrumentation/opencensus-cpp#289]
The current MSVC version specified is 19, but I don't think that is easy to deduce by everybody. (see https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/)

MSVC 2017 has versions x..y.z where x is MSVC 2015, 2017 etc, y is the update number and z is the bugfix/patch-number.

I'm testing on MSVC 2017 15.9.7 (latest update and patch version)

**Comment by g-easy** [comment]
Can you tell what Appveyor is using?

**Comment by meastp** [comment]
According to the documentation: https://www.appveyor.com/docs/windows-images-software/#visual-studio-2017 -> 15.9.6.

15.9 is the most important bit - the last is just patch version and these are released quite often.

**Comment by g-easy** [comment]
IMO we should specify this (and the travis clang and gcc versions) in the topmost README.md

"Support" so far has been a bit ad-hoc. We merge PRs that improve Windows support (e.g. #283) and also Sturdy and I spent some time trying to generally make things build, but not all of OpenCensus is built and tested on Appveyor yet. PRs welcome. :)

**Comment by meastp** [comment]
Could you specify exactly what's missing for Windows / MSVC support? Perhaps a followup issue with a list of all known missing functionality, like with the cmake followup issue? :)

**Comment by g-easy** [comment]
IMO what's missing is "build and test everything on Appveyor." As in `blaze test //...`

This issue is related to https://github.com/census-instrumentation/opencensus-cpp/issues/6

**Comment by g-easy** [comment]
Is this issue resolved now that the MSVC version is specified? We still have #6 to track Windows CI.
