### ISSUE TITLE
Memory leak when not calling Span::End

### ISSUE THREAD

**Issue by Oberon00** [census-instrumentation/opencensus-cpp#303]
In the constructor, a span adds itself to the running span store. However, it is only removed from there in End(). Since a span has no user-defined destructor, this leads to a memory leak if End() is not called on the span.

**Comment by g-easy** [comment]
This is by design. Spans are not RAII, although we are considering adding a ScopedSpan wrapper around Span.

**Comment by Oberon00** [comment]
I understand that spans should not end themselves automatically, but leaking them in the running span store still sounds like a bug to me.

**Comment by g-easy** [comment]
The running span store holds all active spans, and is intended for e.g. building z-pages.

My view is that leaking a Span is not different from leaking an object - it's a bug in the caller and not something we should try to "mitigate."

**Comment by jinmel** [comment]
Could we close this issue since we can address this issue with #327?

**Comment by g-easy** [comment]
I think so.
