### ISSUE TITLE
feature request: WithSpan should call End() on destruction.

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-cpp#323]
related to #303

Though WithSpan is a 'scoped' span, it seems weird that we have to call End() explicitly.

this doesn't seem so clean at all.

```c++
WithSpan ws(Span::StartSpan("test_span", &GetCurrentSpan());
...
GetCurrentSpan().End();
```

**Comment by jinmel** [comment]
Or we should have a StartScopedSpan static method on Span class.

**Comment by g-easy** [comment]
`WithSpan` is purely about manipulating context and it explicitly should *not* end the span when it falls out of scope.

How can we clarify the documentation around this?

**Comment by jinmel** [comment]
'with' makes it sound like a scoped variable that is destroyed.

Do we have plans for implementing scoped span?

2019년 5월 30일 (목) 오전 9:37, easy <notifications@github.com>님이 작성:

**Comment by jinmel** [comment]
@g-easy Or could we add a boolean variable like 
```c++
WithSpan(const span& span, bool end_span = false);
```

**Comment by jinmel** [comment]
https://github.com/census-instrumentation/opencensus-java/blob/c943c6c63637cc866e92b90dae0e48dccd488130/api/src/main/java/io/opencensus/trace/SpanBuilder.java#L252

This implementation is quite notable.
