### ISSUE TITLE
Stackdriver exporter: support exporting GCP metrics (MonitoredResource)

### ISSUE THREAD

**Issue by bianpengyuan** [census-instrumentation/opencensus-cpp#334]
Currently stackdriver exporter could only export custom metrics with `Global` MR. It seems easy to add support to export GCP metrics with predetermined MR, such as [Istio metrics](https://cloud.google.com/monitoring/api/metrics_anthos#anthos-istio.io). We can achieve this by extending stackdriver options to have monitored resource type and labels, which overwrite `Global` MR when constructing time series.

@g-easy

**Comment by g-easy** [comment]
Should this configuration be per-view rather than in the exporter options?

https://github.com/census-instrumentation/opencensus-cpp/blob/a506cf846edca75b93e5457aca51c568378201be/opencensus/exporters/stats/stackdriver/internal/stackdriver_utils.cc#L184

c @bogdandrutu

**Comment by g-easy** [comment]
Related issue: #291

**Comment by bianpengyuan** [comment]
Per view would be better, though I don't know if it is appropriate to add stackdriver specific concept into view.

Also with ability to exporting GCP metrics, I think metric descriptor registration does not need to happen for every view right?

**Comment by g-easy** [comment]
Alternatively, we could add per-view overrides to the exporter rather than the view.
