### ISSUE TITLE
Optimistic stackdriver metric creation

### ISSUE THREAD

**Issue by prateekr** [census-instrumentation/opencensus-cpp#337]
Stackdriver exporter attempts to create the descriptor and only adds it to the exported view whitelist if the call succeeds (i.e. stackdriver confirms with Ok status).

https://github.com/census-instrumentation/opencensus-cpp/blob/858195c5cfc3d450880c583d299a623d2add7b0d/opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc#L155-L163

It'd be good to assume success (either previous or upcoming) and add it to `registered_descriptors_` before attempting to call stackdriver.  I.e it's quite likely the metric created already either because the metric is not brand new or one of the other hundreds of instances had a successful call.  To reiterate, rather than requiring them all succeed, I think it's valuable to only require one to succeed.

Java stackdriver appears to follow this proposal as well: https://github.com/census-instrumentation/opencensus-java/blob/0fa55640bdda66a7be4b67b6b2aecc6961b7ca3f/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java#L95

It is a tad awkward in Java land as the first attempt will fail, but the following updates will succeed even on metric descriptor creation failure.

cc: @g-easy @bogdandrutu

**Comment by prateekr** [comment]
Gentle PING?

**Comment by g-easy** [comment]
What's the problem we want to solve here? Does the first export take too long?

From my reading, the difference between Java and C++ is that C++ will retry failed CreateMetricDescriptor RPCs. Java will remember the failure as a success which I guess will cause partial failures in the CreateTimeSeries RPC?

We can make C++ do the same but it doesn't seem like an ideal solution.

**Comment by prateekr** [comment]
Good points; I don't see a compelling reason to progress here; will go ahead and close.
