### ISSUE TITLE
StackdriverExporter: Register should accept grpc channel

### ISSUE THREAD

**Issue by mandarjog** [census-instrumentation/opencensus-cpp#342]
`StackdriverExporter::Register()` creates a custom grpc channel which is not configurable.
It should accept a grpc channel in during registration.

Use cases
1. Support Envoy google-grpc, so that it can be configured externally.
2. Stub and testing.

@g-easy @bogdandrutu

**Comment by g-easy** [comment]
Please take a look at PR #341.

**Comment by g-easy** [comment]
#341 took care of Stackdriver Trace, I'll take care of Stackdriver Stats in a followup PR.
