### ISSUE TITLE
Allow exporting views with Delta aggregation window

### ISSUE THREAD

**Issue by bianpengyuan** [census-instrumentation/opencensus-cpp#362]
Currently view could be registered to use Delta aggregation window:
https://github.com/census-instrumentation/opencensus-cpp/blob/36e10cb7aba4a024f97c8cc4f81a57103ed7baee/opencensus/stats/internal/set_aggregation_window.h#L28

but it cannot be registered to export:
https://github.com/census-instrumentation/opencensus-cpp/blob/36e10cb7aba4a024f97c8cc4f81a57103ed7baee/opencensus/stats/internal/view_descriptor.cc#L81

@g-easy @bogdandrutu  Is there any reason to make it not available for exporting? It would help Stackdriver exporter recovering from timeseries out of order writes issue. Specifically Istio is migrating from one telemetry exporting source to another, which could introduce a brief period with double exporters. WIth cumulative aggregation window, if the old exporter wins the race, the new exporter can never recover from out of order writes unless restart it.

cc @mandarjog @kyessenov

**Comment by kyessenov** [comment]
Generally, how do we make sure Envoy opencensus-cpp library can recover from errors without restarting the parent process?

**Comment by bianpengyuan** [comment]
At least in Stackdriver stats exporter I don't think there is recovery mechanism, just error logs.

**Comment by bianpengyuan** [comment]
I did some test with the following diff and it works well. Note it seems like the end time of a point and the start time of the next point have to be different, otherwise Stackdriver UI cannot do rate correctly..
```
diff --git a/opencensus/stats/internal/view_data_impl.cc b/opencensus/stats/internal/view_data_impl.cc
index a4991fd..fadd8b2 100644
--- a/opencensus/stats/internal/view_data_impl.cc
+++ b/opencensus/stats/internal/view_data_impl.cc
@@ -253,7 +253,7 @@ ViewDataImpl::ViewDataImpl(ViewDataImpl* source, absl::Time now)
     : aggregation_(source->aggregation_),
       aggregation_window_(source->aggregation_window_),
       type_(source->type_),
-      start_time_(source->start_time_),
+      start_time_(source->start_time_ + absl::Seconds(1)),
       end_time_(now) {
   switch (type_) {
     case Type::kDouble: {
diff --git a/opencensus/stats/internal/view_descriptor.cc b/opencensus/stats/internal/view_descriptor.cc
index 43fcf4f..141b1e9 100644
--- a/opencensus/stats/internal/view_descriptor.cc
+++ b/opencensus/stats/internal/view_descriptor.cc
@@ -75,11 +75,7 @@ ViewDescriptor& ViewDescriptor::set_description(absl::string_view description) {
 }
 
 void ViewDescriptor::RegisterForExport() const {
-  if (aggregation_window_.type() == AggregationWindow::Type::kCumulative) {
-    StatsExporterImpl::Get()->AddView(*this);
-  } else {
-    std::cerr << "Only cumulative views may be registered for export.\n";
-  }
+  StatsExporterImpl::Get()->AddView(*this);
 }
```

**Comment by bianpengyuan** [comment]
@g-easy @bogdandrutu Any feedback on this issue? If the change makes sense I am happy to create a PR for it.

**Comment by bogdandrutu** [comment]
The window notion was added to support interval stats (aka qps in last minute). In order to support deltas you need to add a getViewDataAndReset function at the view level. So that way you get the current value and reset (which means the start time is reset).

But to understand better your issue, you try to export the same timeseries twice? This is not supported by stackdriver, you need to uniquely identify each timeseries.

**Comment by bogdandrutu** [comment]
The main reason why interval stats is not good is because that is an approximation of the last second, also stackdriver requires the new timestamp to be equal with the last end time to consider this a Delta and not an restart of the process.

**Comment by bianpengyuan** [comment]
Yeah, Istio is migrating from a centralized deployment which exports Stackdriver metrics to a proxy based exporter:
![Screenshot from 2019-07-30 10-16-19](https://user-images.githubusercontent.com/34738376/62150568-320b4400-b2b3-11e9-99f8-99048809a169.png)

When proxy upgraded, the reporting pipeline will switch from 2 to 1, but it is possible that Mixer buffers some data and will still make a report calls after the switch, so there could be a race between Mixer and proxy exporter. If proxy loses the race, with cumulative view, it will never recover from out of order writes.

There is already a method to get delta view and reset start time:
https://github.com/census-instrumentation/opencensus-cpp/blob/ddb869dc023a16a05f7c76f7b37deadce1c02ef8/opencensus/stats/internal/view_data_impl.cc#L145

I tried with the new timestamp equal to the last end timestamp, however Stackdriver UI rendered weirdly. It takes the delta of 10s (default export interval) and align it into 1m interval without summing, e.g. for a workload that receives 60 qps, the graph will just show 10 qps, but after changing start time to be different from last end timestamp by adding 1 nanosecond, the graph shows the correct value.

**Comment by bianpengyuan** [comment]
Based on offline discussion, due to the potential risk and amount of work needed to support delta view exporting across languages, it is not going to land easily. An ok workaround is to introduce some diff to label values so that time series could be distinguished by SD, which we are going to give it a try.

**Comment by g-easy** [comment]
i.e. To make mixer and proxy write to two different timeseries.
