### ISSUE TITLE
Make Stackdriver exporter selectively fill in opecensus_task label

### ISSUE THREAD

**Issue by bianpengyuan** [census-instrumentation/opencensus-cpp#372]
Currently StackdriverOption fill in opecensus_task with a default value (`cpp-{PID}@{HOSTNAME}`) when it is empty:
https://github.com/census-instrumentation/opencensus-cpp/blob/7063ccb607bced1f48eb6a89da1eed162788d783/opencensus/exporters/stats/stackdriver/stackdriver_exporter.h#L35-L38
However when sd exporter is used to export GCP metrics, opencensus_task label should not be filled. We need a way to make opencensus_task label selectively filled for different metrics.

@g-easy @bogdandrutu

**Comment by g-easy** [comment]
How about something like https://github.com/census-instrumentation/opencensus-cpp/pull/373 so we can add and remove labels on a per-metric basis?

I can't see a precedent in [opencensus-java](https://github.com/census-instrumentation/opencensus-java/blob/89ecd70f633be3e74cd9d9d20934804eebf49ca6/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java) for this API or functionality. @bogdandrutu what do you think?

**Comment by bianpengyuan** [comment]
A related issue is `CreateMetricDescriptor` is called for all metrics, including GCP metric. Stackdriver returns permission error on such call:
```
CreateMetricDescriptor request failed: PERMISSION_DENIED: User xxx@developer.gserviceaccount.com does not have permission to write to metric istio.io/service/client/request_count
```

Do we want to introduce some field for special handling of GCP metrics, or do we want to solve opencensus_task label issue with this one together (i.e. an indicator of a metric is GCP metric, so don't add opencensus_task label and don't send `CreateMetricDescriptor` request for that metric)

**Comment by g-easy** [comment]
Is this more generic than just GCP? Should there be a `map<string,bool> per_metric_do_not_create_descriptor`?

**Comment by bianpengyuan** [comment]
Yeah, that works for me.
