### ISSUE TITLE
grpc example build failed

### ISSUE THREAD

**Issue by snowcrumble** [census-instrumentation/opencensus-cpp#405]
I am building with bazel docker image:
`l.gcr.io/google/bazel:0.17.1`

Error output:
`
bazel build :all
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /Users/snow/work/cpp/opencensus-cpp/bazel/deps.bzl:2:1: file '@bazel_tools//tools/build_defs/repo:utils.bzl' does not contain symbol 'maybe'
ERROR: error loading package '': Extension file 'bazel/deps.bzl' has errors
ERROR: error loading package '': Extension file 'bazel/deps.bzl' has errors
INFO: Elapsed time: 2.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
root@1a77b309d378:/Users/snow/work/cpp/opencensus-cpp/examples/grpc# bazel build :all
ERROR: /root/.cache/bazel/_bazel_root/3285621c43e9f9a7d3bb17ff9f2dfeb2/external/com_github_grpc_grpc/bazel/generate_cc.bzl:44:55: name 'ProtoInfo' is not defined
ERROR: Skipping ':all': while parsing ':all': error loading package 'examples/grpc': Extension 'bazel/generate_cc.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: while parsing ':all': error loading package 'examples/grpc': Extension 'bazel/generate_cc.bzl' has errors
INFO: Elapsed time: 39.454s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: examples/grpc
`

**Comment by g-easy** [comment]
Are you able to use bazel 1.1.0 instead?

In #400 I updated the version of bazel we use on Travis because one of our deps needed a newer version.
