### ISSUE TITLE
Make stats export interval configurable

### ISSUE THREAD

**Issue by bianpengyuan** [census-instrumentation/opencensus-cpp#412]
Right now export interval is set to be 10s by default and is not configurable. However each backend has its own recommended minimum exporting period, i.e. stackdriver recommends minimum exporting period is 1 min. Opencensus go library supports configurable export interval: https://github.com/census-instrumentation/opencensus-go/blob/df6e2001952312404b06f5f6f03fcb4aec1648e5/stats/view/worker.go#L119 , we should consider adding it here as well.

@g-easy @bogdandrutu 

FYI @quentinmit @mandarjog

**Comment by bogdandrutu** [comment]
@bianpengyuan is this for stats?

**Comment by bianpengyuan** [comment]
Yes.

**Comment by bogdandrutu** [comment]
Yes we should have the interval configurable.

**Comment by mandarjog** [comment]
The default of stats export every 10s is too small per SD, so it should be raised to 1min in addition to making it configurable.

**Comment by bianpengyuan** [comment]
@mandarjog The default interval is shared by all exporters, so not sure if it is ok to uniformly raise it. Go library supports per view configurable export interval.

**Comment by bianpengyuan** [comment]
@bogdandrutu Can we come a proper API for this soon? @g-easy mentioned that implementation is blocked by API decision. This is becoming more and more pressing since it blocks productionization of using OC library for SD stats reporting. 

cc @douglas-reid FYI
