### ISSUE TITLE
google/benchmark dropping master branch

### ISSUE THREAD

**Issue by maslick** [census-instrumentation/opencensus-cpp#457]
Seems like ``google/benchmark`` has dropped master branch (in favor of main) [1], and since you're relying on ``google/benchmark``, our builds are failing with: 
```
-- Dependency: benchmark (BUILD_TESTING=ON)
[1/9] Creating directories for 'benchmark-populate'
[1/9] Performing download step (git clone) for 'benchmark-populate'
Cloning into 'benchmark-src'...
fatal: invalid reference: master
CMake Error at benchmark-subbuild/benchmark-populate-prefix/tmp/benchmark-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'
```

[1] https://github.com/google/benchmark/issues/1116

**Comment by maslick** [comment]
Created a PR: https://github.com/census-instrumentation/opencensus-cpp/pull/458

**Comment by jsuereth** [comment]
CLosing this as the PR submitted.  Looks like cc_rules also has the same issue.
