### ISSUE TITLE
Fallthrough return in functions returning from a switch without a default.

### ISSUE THREAD

**Issue by isturdy** [census-instrumentation/opencensus-cpp#79]
Our build is presently cluttered with warnings that functions that return from a switch on an enum. Absl uses a return outside the enum to suppress these warnings; I think we should either follow suit (possibly with an `assert(false)`) or add build options to silence the warning.

**Comment by g-easy** [comment]
These warnings come from gcc not being good enough at static analysis. I don't want to add too much noise to our source (or the generated code) just to quiet these warnings.

**Comment by g-easy** [comment]
I agree on not silencing genuine errors.

How does `assert(false);` affect the generated code?

If the answer is "non zero", how about `__builtin_unreachable`?

**Comment by isturdy** [comment]
`assert(false)` does still add a call in GCC's -O2 assembly. `__builtin_unreachable` does not, but I think making that portable would involve even worse clutter.

Seems like there is no great solution for this--I am okay with dropping it, particularly with all the warnings the proto and gRPC codegens create.

**Comment by g-easy** [comment]
IMO keep this issue around at low priority in case someone else has a better idea. Thanks for the gcc followup.

On a related note, I like to leave out the `default:` case because it turns a missing case into a compile-time error. `default` potentially silences a genuine error.

**Comment by isaachier** [comment]
I've wondered about this and decided to use this "pattern" in general:

```
enum { a, b, c };

switch (x) {
case a:
... 
case b:
... 
default:
  assert(x == c);
} 
```

Also, GCC isn't the issue. C++ allows for casting any value to an enum so the cases could never include these values outside the normal enum range.

**Comment by isturdy** [comment]
That causes false alarms for the warning "enum not handled in switch", which typically does need attention, and is very helpful for catching omissions when adding an enum value.

**Comment by isaachier** [comment]
What about the case label immediately followed by default and assertion? I agree in general it's nice to see all values but not sure there's a great way to deal with this for GCC.
